repos:
  - repo: local
    hooks:
      - id: collapse-blank-lines
        name: Collapse Multiple Blank Lines
        entry: python3 -c "import sys, re; [open(f, 'w', newline='').write(re.sub(r'(\r?\n){3,}', r'\1\1', c)) for f in sys.argv[1:] for c in [open(f, 'r', newline='').read()]]"
        language: system
        files: '\.(v|sv|vh|svh|cpp|h|sh|md)$'

      - id: verible-verilog-format
        name: Verible Verilog Format
        entry: verible-verilog-format
        args:
          - --flagfile=.verible-format
          - --inplace
        language: system
        files: '\.(v|sv|vh|svh)$'

      - id: verible-verilog-lint
        name: Verible Verilog Lint
        entry: verible-verilog-lint
        args:
          - --rules_config_search
        language: system
        files: '\.(v|sv|vh|svh)$'

      - id: verilator-lint
        name: Verilator Linting
        entry: bash tools/verilator_lint.sh
        language: system
        pass_filenames: false
        files: '\.(v|sv|vh|svh)$'